### ISSUE TITLE
Localization of control labels

### ISSUE THREAD

**Issue by trebmuh** [amsynth/amsynth#141]
Hi @nickdowell 

For now, the menu items and other stuffs are translatable. Would that be possible to have the GUI stuff translatable as well? I mean here the "buttons texts" (WAVEFORM, SHAPE, ATTACK, DECAY,...etc).

**Comment by nickdowell** [comment]
Currently those bits of text are included in the background image. Because the UI has fixed positions and sizes for each control, it would not be able to adapt to certain words being longer in some languages. Therefore it would be quite difficult to make them translatable and do it well in the current implementation... so I'm not sure it's worth the effort. Will add this as an aim for #37 

That said, pull requests are welcome if you feel like taking on making the control labels translatable!

**Comment by trebmuh** [comment]
OK, fair enough. I hope some programming people will jump in for that! (_I'm not such a programming person_)

**Comment by nickdowell** [comment]
Closing because I don't think this is necessary and would break 3rd party skins (like [Etna](https://turiscandurra.com/2018/03/etna-amsynth-skin/))

Furthermore amsynth's UI is meant to look a bit like a piece of hardware, and hardware synth labels are always in English.
