### ISSUE TITLE
Install location?

### ISSUE THREAD

**Issue by charlesreid1** [amsynth/amsynth#142]
### Expected behavior

Readme or installer or website does not mention where amsynth is installed to when users run the automatic packaged installer. I cannot find it.

### Actual behavior

Running the Mac .pkg installer works, the installer completes successfully. However, I can't find the `amsynth` binary. There is no binary `amsynth` in `/Applications` or in home directory or in `/usr` or in `/usr/local`, so I have no idea how to start the amsynth program or where it was installed to.

### Information

  - Which version of amsynth are you using? Mac
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST) standalone application
  - If using amsynth as a plugin, which host application are you using?
  - Which operating system & version are you using? Mac OS X 10.13.6

### Steps to reproduce the behavior

  1. Download the Mac .pkg installer
  2. Run the Mac .pkg installer to completion

Thank you for any insight you can give!

**Comment by nickdowell** [comment]
The Mac version of amsynth is an AudioUnit plug-in, not a stand-alone application.

It installs into `/Library/Audio/Plug-Ins/Components/amsynth.component`

I'm not sure if it works on current version of macOS, it was built in 2014...

**Comment by theOnlyAitor** [comment]
made an account just to post this but im having the exact same problem on a 10.11.16. The whole installer works perfectly but then the file is nowhere to be found. Tried that folder you mentioned too but it didnt exist on my computer. Is there any other way to just diectly install the file to whatever folder i want?

**Comment by nickdowell** [comment]
I'm not sure what's could be going wrong here.

The installer installs the amsynth plug-in in /Library/Audio/Plug-Ins/Components (note this is the top-level directory, not in your user folder)

If the plug-in is installed, you should see it as available in your Audio Unit host application (e.g. Logic or GarageBand) and should be listed when you run the following command in Terminal:

```
$ auval -s aumu

    AU Validation Tool
    Version: 1.6.1a1 
    Copyright 2003-2013, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

aumu Amsy Nicd  -  Nick Dowell: amsynth
```

It does not make sense to install the file to whatever folder you like, because then it would not show up in the list of available plug-ins for your DAW.

Note that there is currently no standalone app version of amsynth on macOS.

**Comment by nickdowell** [comment]
The mac installer now includes a welcome page that explains what is installed, and where.
