### ISSUE TITLE
Ubuntu 19.10 version (1.8.0-1) crashing on MIDI programme change

### ISSUE THREAD

**Issue by ondinegreen** [amsynth/amsynth#150]
When I run my Rosegarden sequencer with amsynth on the latest Ubuntu Studio (Ubuntu eoan package version), the synth accepts a first MIDI program change; but when I try to send another one (i.e. start a new song), I get a crash with:

(amsynth:4683): GLib-GObject-CRITICAL **: 16:16:01.750: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Segmentation fault (core dumped)

**Comment by nickdowell** [comment]
This appears to be due to a bug that was fixed in release 1.9.0

Please re-open this issue if you find the crash is still there in 1.9.0

P.S. you can install a more recent version of amsynth from the PPA
* https://code.launchpad.net/~nick-nickdowell/+archive/ubuntu/amsynth-develop
* https://code.launchpad.net/~nick-nickdowell/+archive/ubuntu/amsynth-develop/+sourcepub/10404176/+listing-archive-extra
