### ISSUE TITLE
MIDI CC 123 to stop all notes

### ISSUE THREAD

**Issue by milkmiruku** [amsynth/amsynth#73]
I'm trying out amsynth but it doesn't seem to respect a CC 123 to stop all notes in the case when a pattern stops before note off events.

**Comment by nixxcode** [comment]
Sorry not sure what you mean by "in the case when a pattern stops before note off events"

What are the steps to reproduce the issue?

**Comment by nixxcode** [comment]
Closing because I do not know how to reproduce the issue.

**Comment by dddomin3** [comment]
I don't have the issue, since it's not... really a solvable issue in amSynth specifically (unless you make MIDI panic assignable via MIDI CC, which might be weird).

If you use a step sequencer, and you stop it, it may be stopped before a note_off midi message is sent, which would cause a hanging midi note. MOST sequencers come with the functionality of tapping stop a bunch, and it will send a global note off.
